* Timesheets
| S.NO | NAME     | -DATE | TASK | TIME | RESULT |
|------+----------+-------+------+------+--------|
|    1 | SRIPATHI |       |      |      |        |
|      |          |       |      |      |        |
|      |          |       |      |      |        |
|      |          |       |      |      |        |
|      |          |       |      |      |        |
|      |          |       |      |      |        |
* Issues
** Blockers
*** Database
- E-R diagramme itself is not matching with mysql implementation.
  there are 14 tables in E-R diagrame and in implementation part there are 16 tables.
- The relationships between few tables like =users= and =user_details= is like meaning less. Instead of one-one relationship they have implemented one-many
- As mentioned in E-R model there are no foreign keys set to tables.
- There are two tables for users: va_users and va_user_users. A lot of data is redundant.
- And va_admin_users and va_users as well as va_admin_details and va_user_details redundant. 
- All the users can be generalised to one table and user details to another table with an attribute 
  specifying the role the user as admin/outreach coordintator/nodal coordinator.
  
*Conclusion :*
- Therefore if we host this application using this database implementation and if someone adds or deletes outreach coordinators or 
  nodal coordinators the updates wont be cascaded so for example if an outreachcoordinator named oc1 created nodal 
  coordinators nc1,nc2,nc3 and then admin deleted oc1 then it nc1,nc2,nc3 will still have oc1 as their outreachcoordinator. 
  This should be avoided by using foreign key constraints with cascading update/delete actions or by rejecting the delete.
- if it’s hosted without making these modifications and it would be almost impossible to recover data integrity manually.  
  Also these modifications would require a lot of changes in code. All the code will have to be reviewed again after these modifications. 

*** Coding
- Indentation is very bad in many files.
- There were no comments for many files.
- Script and style tags are used at many places in the code. Its better to define them at the beginning of the file.
*Conclusion:* Therefore It is very difficult to understand code without comments and also we were struggling with indentation.
*** Interface
**** Admin Interface
- Admin loggin itself is not working after few issues resolved. Therefore we coudn't test all admin roles with latest changes.
**** Outreach Interface
- Outreach coordinator unable to upload trainng reports(Photos & Documents). It's giving error.
- There were no form validation for(No.of workshops,No.of Participates and No.of experiments) it is accepting
  strings instead of digits.
- Single nodal center assigned to different coordinators.(need clarification)
- Can same user can acts as both nodal and outreach coordinator( need clarification)
- There is no approve button after nodal coordinator submits the reports.
- There is no view is implemnted for submitted documents. Therefore he can't view and approve them.
*Conclusion:* If we host this application with current status outreach coordinator can't recieve documents submitted by nodal coordinators.
              there will be data lost.
**** Nodal Coordinator

- There were no form validations for all the text feilds while creating new workshop. Like date field is accepting special charachters like &**&&!@3.
- After workshop is done. Nodal coordinator is unable to upload multiple photos.
  While uploading files there is no file format validation instead he can upload any file formats like .mp3 and .mp4.
- While creating new workshop save button is not working it showing database errors
** Others issues
Cane be found here https://github.com/Virtual-Labs/outreach-portal/issues
** Conclusion

